
services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - D:/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-teste-network
  
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-teste-network

networks:
  postgres-teste-network:
    driver: bridge
